[test] full_write tc 추가
skm04614/ProjectTeamD pull request #15
Opened 2024-06-18 05:33 UTC by ymabcd

2024-06-18 05:35 UTC, ymabcd commented on tests/test_custom_shell.py
> +        return hex_values
nand.txt 파일 내용이 "[0] 0x00000000" 포멧으로 저장되기 때문에 hex value를 추출하기 위한 함수 추가

2024-06-18 06:06 UTC, dolgyyyy requested changes
parts = line.strip().split(' ')
여기에 코멘트 달았습니다. 감사합니다.

2024-06-18 06:06 UTC, dolgyyyy commented on tests/test_custom_shell.py
> +            parts = line.strip().split(' ')
strip()하고 split(' ')하면 의도한 결과가 나오지 않을 거 같습니다.

2024-06-18 06:10 UTC, ymabcd commented on tests/test_custom_shell.py
> +            parts = line.strip().split(' ')
'[0] 305463295\n' 포멧으로 저장되기에
line.strip()으로 '[0] 305463295\n' -> '[0] 305463295' 변경되고,
split(' ')으로 2개 요소로 구분하였습니다.

parts는 한 라인이 아래와 같이 구분됩니다.
0: [0]
1: 305463295

혹시 문제가 있을까요?

2024-06-18 06:16 UTC, dolgyyyy commented on tests/test_custom_shell.py
> +            parts = line.strip().split(' ')
앗 죄송합니다. full_write만보고 전체를 받아서 처리하는 줄 알고 착각했습니다.😂😂😂

2024-06-18 06:17 UTC, dolgyyyy approved these changes
수고하셨습니다.👍👍

2024-06-18 07:19 UTC, banggeut01 approved these changes
full_wirte test 확인하였습니다~! 고생많으셨습니다.

2024-06-19 01:37 UTC, dolgyyyy approved these changes
수고하셨습니다.

2024-06-19 01:38 UTC, merged