[feature] SSD write 구현부 업데이트
skm04614/ProjectTeamD pull request #22
Opened 2024-06-18 07:17 UTC by hyugi012

SSD write unittest를 위한 구현부 업데이트

2024-06-18 07:21 UTC, banggeut01 approved these changes
SSD Write 기능에서 invalid 처리한 것 확인하였습니다 ~! 고생많으셨습니다. 👍

2024-06-18 07:24 UTC, dolgyyyy approved these changes
오늘 하루 수고 많으셨습니다.

2024-06-18 07:24 UTC, dolgyyyy commented on ssd/ssd.py
> +    def assert_invalid_input(self, lba, val):
invalid input을 따로 함수화하는 방법은 아주 탁월하신 거 같습니다.
프로젝트의 일관성을 위해 아래와 같은 방법은 어떨까요?
```
def assert_invalid_input(self,
                         lba: int,
                         val, int
```

2024-06-18 07:24 UTC, dolgyyyy commented on ssd/ssd.py
> +        if type(lba) is not int or type(val) is not int:
상관은 없지만 PEP 8에서는 
type 비교는 isinstance를 사용하라고 가이드 되어 있네요~
![image](https://github.com/skm04614/ProjectTeamD/assets/171532670/c4b47dab-db8f-43c0-bcc4-535866a9600f)

2024-06-18 07:25 UTC, skm04614 requested changes

2024-06-18 07:25 UTC, skm04614 commented on ssd/ssd.py
> +        if len(f"{val:X}") != 8:
if not 0x0 <= val <= 0xFFFFFFFF:와 동일한 check문이므로 필요 없습니다.

2024-06-18 07:25 UTC, skm04614 commented on ssd/ssd.py
> +        if type(lba) is not int or type(val) is not int:
이 것은 type error로 처리해야 합니다.

2024-06-18 07:25 UTC, skm04614 commented on ssd/ssd.py
> +        self.assert_invalid_input(lba, val)
assert문을 따로 함수로 refactoring하여 얻는 이점보다 실이 크다고 생각됩니다. 함수 호출부만 보고 어떤 exception을 띄우는지 확인하기 위해 타고 들어가야 하는 depth를 늘리는 이점이 없어보입니다.

2024-06-18 07:31 UTC, hyugi012 commented on ssd/ssd.py
> +        if len(f"{val:X}") != 8:
0x1234와 같이 10자리(0x00001234)가 아닐 경우 걸러내는 경우를 위해 생성한 case 입니다.

2024-06-18 07:33 UTC, hyugi012 commented on ssd/ssd.py
> +        if type(lba) is not int or type(val) is not int:
수정하겠습니다!

2024-06-18 07:36 UTC, skm04614 commented on ssd/ssd.py
> +        if len(f"{val:X}") != 8:
그런 edge 케이스가 있었군요, 감사합니다 :)

2024-06-18 07:36 UTC, hyugi012 commented on ssd/ssd.py
> +        self.assert_invalid_input(lba, val)
invalid input case가 추가될 경우 write 함수 초반부가 지저분해 보일 수 있어 함수화 하는게 맞다고 생각했습니다. refactoring 강의에서도 항상 함수화 해왔었구요. depth가 깊지 않고 error를 print해주기 때문에 실이 크다고 생각은 하지 않습니다. 오히려 추가적인 invalid case가 생길 경우 추가, 관리하기 좋다고 생각됩니다.

2024-06-18 07:37 UTC, hyugi012 commented on ssd/ssd.py
> +        if type(lba) is not int or type(val) is not int:
isinstance로 수정하는것이 깔끔할 것 같네요! 의견 감사합니다!

2024-06-18 07:37 UTC, hyugi012 commented on ssd/ssd.py
> +    def assert_invalid_input(self, lba, val):
오 미처 확인하지 못한 부분이네요. 감사합니다!

2024-06-18 07:41 UTC, dolgyyyy commented on ssd/ssd.py
> +        self.assert_invalid_input(lba, val)
오 넵. lba, val을 각각 관리하는 것도 고려해 보면 좋겠습니다.
write에서는 read는 lba만 인자로 받아서 각각 관리한다면 좀 더 범용적일 거 같습니다.

2024-06-18 07:44 UTC, hyugi012 commented on ssd/ssd.py
> +        self.assert_invalid_input(lba, val)
넵 read에서도 중복으로 사용되는 부분이 있다면 LBA, val 분리하는 것이 좋아보이네요! 😊

2024-06-19 00:06 UTC, dolgyyyy approved these changes
수고하셨습니다. 오늘도 화이팅~~👍👍

2024-06-19 00:06 UTC, dolgyyyy commented on tests/test_ssd.py
> +    def test_exception_when_invalid_arg_for_write(self):
test 함수명이 길면 안 된다는걸 처음 알았습니다 ㅎㅎ

2024-06-19 00:53 UTC, skm04614 commented on ssd/ssd.py
> +        if len(f"{val:X}") != 8:
생각해보니 어차피 0x000000000001234 == 0x1234이기 때문에 예외 처리하지 않아도 됩니다.

2024-06-19 00:53 UTC, skm04614 commented on ssd/ssd.py
> +        self.assert_invalid_input(lba, val)
강의에선 너무 과하게 모든 것을 다 refactor하는 예시를 들었다고 생각합니다. 

이 case에서는 lba, val에 대한 range check (value error)과 type check (type error) 외에 추가할 케이스가 없다고 생각 되며, 동일한 check를 진행하는 곳이 여러 곳이 아니기 때문에, 해당 exception을 refactor하는 것이 크게 필요 없다고 사료됩니다.

2024-06-19 00:53 UTC, skm04614 commented on ssd/ssd.py
> +        self.assert_invalid_input(lba, val)
https://github.com/pypa/pip/blob/main/src/pip/_internal/network/session.py

pip 소스코드인데, 보시면 raise 구문을 따로 refactor하여 함수로 빼지 않습니다. 함수 안에서 invalid 상황에 대한 처리를 직접 raise하는 방식으로 처리하는 것이 옳다고 생각됩니다.

그리고 그와 별개로 assert_invalid_input에서 input이 lba, val를 check하는 함수인지 명확히 드러나지 않아 최소한 이름은 변경되어야 한다고 생각됩니다.

2024-06-19 00:53 UTC, skm04614 commented on ssd/ssd.py
> +        if len(f"{val:X}") != 8:
위 이유로 아래 코드는 dead code입니다.

```
if len(f"{val:X}") != 8:
  raise ValueError("The number of target value is not 10.")
```

2024-06-19 01:24 UTC, hyugi012 commented
SSD write value 타입 변경하여 exception, unittest 수정 하였습니다.

2024-06-19 01:37 UTC, hyugi012 commented on ssd/ssd.py
> +        if len(f"{val:X}") != 8:
세부 규정에 0x 포함 10자리 입력이 필수로 되어있어 exception 코드 추가합니다.

        if not len(val) == 10:
            raise ValueError("target value must be 10 digits. (ex)0x00001234")
        try:
            val = int(val, 16)
            if not 0x0 <= val <= 0xFFFFFFFF:
                raise ValueError("val is out of range [0x00000000, 0xFFFFFFFF].")
        except ValueError:
            raise ValueError("val is not hex value")

2024-06-19 01:41 UTC, ymabcd approved these changes
😊 수고하셨습니다.

2024-06-19 01:41 UTC, skm04614 requested changes

2024-06-19 01:41 UTC, skm04614 commented on tests/test_ssd.py
> +                self.__ssd.write(lba, '0x100')
"0x00000100"으로 수정 부탁드립니다.

위 tc는 lba out of bounds 확인용 tc이기 때문에 val은 valid 값으로 고정 필요합니다.

2024-06-19 01:41 UTC, skm04614 commented on tests/test_ssd.py
> +                self.__ssd.write(lba, '0x100')
"0x00000100"으로 수정 부탁드립니다.

위 tc는 lba out of bounds 확인용 tc이기 때문에 val은 valid 값으로 고정 필요합니다.

2024-06-19 01:41 UTC, skm04614 commented on tests/test_ssd.py
> -            with self.assertRaises(TypeError):
type mismatch 확인용이므로, TypeError만 잡아야 합니다.

2024-06-19 01:41 UTC, skm04614 commented on tests/test_ssd.py
> +    @skip
skip 태그 제거 부탁드립니다.

2024-06-19 01:41 UTC, skm04614 commented on tests/test_ssd.py
> +    @skip
skip 태그 제거 부탁드립니다.

2024-06-19 01:46 UTC, closed without merging