[test] unit test code for testapp1, 2
skm04614/ProjectTeamD pull request #44
Opened 2024-06-19 07:24 UTC by hyugi012

이것도 시간이 좀 걸리는데 우선 추가해봤습니다.

2024-06-19 07:48 UTC, skm04614 requested changes

2024-06-19 07:48 UTC, skm04614 commented on tests/test_custom_shell.py
> +        self.__cshell.fullwrite(test_value)
testapp1을 호출하여 expected 값 나오는지 확인하는 방향으로 작성되어야 할 것 같습니다

2024-06-19 07:48 UTC, skm04614 commented on tests/test_custom_shell.py
> +        for _ in range(30):
마찬가지로 여기서도 testapp2를 호출하여 expected 값 확인하는 방향으로 재작성되어야 할 것 같습니다.

2024-06-19 23:24 UTC, hyugi012 commented on tests/test_custom_shell.py
> +        self.__cshell.fullwrite(test_value)
아 맞네요. 수정 하였습니다.

2024-06-19 23:35 UTC, skm04614 approved these changes
수고하셨습니다 💯

2024-06-20 00:34 UTC, ymabcd approved these changes
수고하셨습니다. 😊

2024-06-20 00:40 UTC, merged